Update 2023-oss-na.md
cncf/tag-env-sustainability pull request #265
Opened 2023-11-02 16:58 UTC by patricia-cahill

Addition of the TAG related talks during KubeCon NA

2023-11-02 17:04 UTC, catblade approved these changes

2023-11-02 17:24 UTC, guidemetothemoon commented
@patricia-cahill I think we need to create a separate article that will contain talks for the KubeCon + CloudNativeCon NA. The one you updated was for Open Source Summit NA event which happened back in May so we need to create a dedicated article to avoid confusion. Would you be able to do that, please?😊

2023-11-02 18:39 UTC, leonardpahlke requested changes
Yes, we need to create a new file. Here: https://github.com/cncf/tag-env-sustainability/tree/main/website/content/events

2023-11-05 22:34 UTC, nikimanoledaki commented
Could we add the following talks as well, please - thank you @patricia-cahill! 🙌 
```
[Cutting Climate Costs with Kubernetes and CAPI - Shiva Rezaie & Steve Francis, Sidero Labs](https://sched.co/1R2p6)

[Sponsored Keynote: Reduce, Reuse, Recycle - Nathan Taber, Head of Product, Kubernetes, Amazon Web Services](https://sched.co/1R4fu)

[Kube-Costbusters: Optimizing Kubernetes Clusters for Efficiency and Epic Savings! - Rachel Leekin & Antoinette Mills, AWS](https://sched.co/1R2r2)

[Where's Your Money Going? the Beginners Guide to Measuring Kubernetes Costs - Mark Poko & JuanJo Ciarlante, Grafana Labs](https://sched.co/1R2vE)
```

2023-11-08 17:36 UTC, closed without merging