Added the blog post
cncf/tag-env-sustainability pull request #424
Opened 2024-05-28 13:44 UTC by akelity

Added the blog post about CNCF Cloud Native Sustainability Week 2024

2024-05-29 15:40 UTC, claire-fletcher requested changes
1 small comment

2024-05-29 15:40 UTC, claire-fletcher commented on website/content/en/blog/2024-05-30-cncf-cloud-native-sustainability-week-2024-is-underway-and-why-you-should-care.md
> +## The CNCF Cloud Native Sustainability Week is YOU!
```suggestion
## The CNCF Cloud Native Sustainability Week needs YOU!
```
The original phrasing doesn't quite sound right. I assume from the next paragraph that the sentiment is asking for help?

2024-05-29 17:11 UTC, savitharaghunathan commented on website/content/en/blog/2024-05-30-cncf-cloud-native-sustainability-week-2024-is-underway-and-why-you-should-care.md
> +Active Participation: Even just attending events, promoting them within your network, and sharing your ideas can help create a more aware and engaged community. Every voice counts, and your contribut
Suggestion: Can we make this is a list? the rendering puts it in a para and it is difficult to read.

2024-05-30 05:46 UTC, guidemetothemoon reviewed
Few minor suggestions - once processed I can approve the PR😊

2024-05-30 05:46 UTC, guidemetothemoon commented on website/content/en/blog/2024-05-30-cncf-cloud-native-sustainability-week-2024-is-underway-and-why-you-should-care.md
> +Active Participation: Even just attending events, promoting them within your network, and sharing your ideas can help create a more aware and engaged community. Every voice counts, and your contribut
```suggestion
* Organizing Events: If you're willing, you can organize an event, support other local gatherings, or virtual sessions. This role is crucial to ensure each event runs smoothly and reaches its full potential.
* Sharing Your Expertise: If you have experience in sustainable practices or cloud native technologies, consider hosting a session or workshop. Sharing your knowledge can have a significant impact and inspire others to adopt sustainable practices.
* Active Participation: Even just attending events, promoting them within your network, and sharing your ideas can help create a more aware and engaged community. Every voice counts, and your contribution can make a difference.
```

2024-05-30 05:46 UTC, guidemetothemoon commented on website/content/en/blog/2024-05-30-cncf-cloud-native-sustainability-week-2024-is-underway-and-why-you-should-care.md
> +Join us in promoting sustainable practices and making a difference. For more information and to sign up as a volunteer, visit the CNCF website.
```suggestion
Join us in promoting sustainable practices and making a difference. For more information and to sign up as a volunteer, visit the [TAG ENV website](https://tag-env-sustainability.cncf.io/events).
```

2024-05-30 06:15 UTC, Nancy-Chauhan approved these changes
Thank you @akelity 🚀

2024-05-30 11:48 UTC, savitharaghunathan reviewed
/lgtm

Thanks everyone for working on this

2024-05-30 11:49 UTC, savitharaghunathan approved these changes

2024-05-30 12:06 UTC, guidemetothemoon approved these changes
LGTM - thanks everyone who contributed and reviewed!

2024-05-30 12:06 UTC, guidemetothemoon commented
@claire-fletcher can you please review to unblock merging of the PR? Thanks!

2024-05-30 14:14 UTC, merged